### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by nixonogoi** [nixonogoi/udacityProgrammingIntro#1]
- [ ] Design database schema
- [ ] Update the tournament.sql file
- [ ] Create database from file
- [ ] Run SQL queries on created DB
- [ ] Write and test each function against tournament_test.py
- [ ] If all functions pass test: 
    - [ ] Redesign Database schema to account for extra points
    - [ ] Update functions as needed
    - [ ] Update the tournament_test.py to include extra tests
- [ ] SIMPLIFY CODE and check STYLING on documents
- [ ] Submit project for review!
- [ ] Keep LEARNING!!!
